# Generated by Django 5.1.1 on 2025-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_final_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='khalti_final_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='khalti_initial_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
