# Generated by Django 5.1.1 on 2025-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PL', 'Plumber'), ('EL', 'Electrician'), ('CA', 'Carpenter'), ('CL', 'Cleaner'), ('ME', 'Mechanic'), ('PA', 'Painter'), ('AC', 'AC Repair'), ('IT', 'IT Support'), ('D', 'Driver')], max_length=2)),
                ('description', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Cost per hour in INR', max_digits=8)),
                ('estimated_time_hours', models.DecimalField(decimal_places=2, help_text='Approximate time required in hours', max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
