# Generated by Django 5.1.1 on 2025-06-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerrating',
            name='appointment',
        ),
        migrations.AddField(
            model_name='workerrating',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.appointment'),
        ),
    ]
