# Generated by Django 5.1.1 on 2025-06-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_remove_workerrating_appointment_and_more'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='workerrating',
        #     unique_together={('worker', 'appointment', 'customer')},
        # ),
        migrations.AddField(
            model_name='worker',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='worker',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerrating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerrating',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='jobs.customer'),
        ),
        migrations.AddField(
            model_name='workerrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workerrating',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='jobs.worker'),
        ),
        migrations.RemoveField(
            model_name='workerrating',
            name='average_rating',
        ),
    ]
