# Generated by Django 5.1.1 on 2025-08-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_workerrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerrating',
            unique_together={('worker', 'appointment', 'customer')},
        ),
    ]
