# Generated by Django 5.1.1 on 2025-09-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_customer_latitude_alter_customer_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='worker_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
