# Generated by Django 5.1.1 on 2025-09-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_appointment_created_at_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='estimated_time_hours',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_available',
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='base_pricing_type',
            field=models.CharField(choices=[('hourly', 'Hourly Rate'), ('sqft', 'Per Square Foot'), ('unit', 'Per Unit/Item'), ('inspection', 'Per Inspection'), ('shift', 'Shift-based'), ('fixed', 'Fixed Price')], default='hourly', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobs.servicecategory'),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('default_pricing_type', models.CharField(choices=[('hourly', 'Hourly Rate'), ('sqft', 'Per Square Foot'), ('unit', 'Per Unit/Item'), ('inspection', 'Per Inspection'), ('shift', 'Shift-based'), ('fixed', 'Fixed Price')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='jobs.service')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.service')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobs.worker')),
            ],
            options={
                'unique_together': {('worker', 'service')},
            },
        ),
        migrations.CreateModel(
            name='WorkerSubTaskPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('hourly', 'Hourly Rate'), ('sqft', 'Per Square Foot'), ('unit', 'Per Unit/Item'), ('inspection', 'Per Inspection'), ('shift', 'Shift-based'), ('fixed', 'Fixed Price')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('night_shift_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_hours', models.PositiveIntegerField(default=1, help_text='Minimum hours for hourly pricing')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.subtask')),
                ('worker_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='jobs.workerservice')),
            ],
            options={
                'unique_together': {('worker_service', 'subtask')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.workersubtaskpricing'),
        ),
    ]
