# Generated by Django 5.1.1 on 2025-09-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_service_is_active_servicecategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subtask_images/'),
        ),
    ]
