# Generated by Django 5.1.1 on 2025-10-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_subtask_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_workers', to='jobs.customer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='jobs.worker')),
            ],
            options={
                'verbose_name': 'Favorite Worker',
                'verbose_name_plural': 'Favorite Workers',
                'unique_together': {('customer', 'worker')},
            },
        ),
    ]
