# Generated by Django 5.1.1 on 2025-10-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_add_new_models_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='previous_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='previous_location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='previous_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='previous_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='previous_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='previous_location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='previous_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='previous_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
