# Generated by Django 5.1.1 on 2025-10-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_customer_previous_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='worker_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workerrating'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_request', 'Appointment Request'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_completed', 'Appointment Completed'), ('appointment_cancelled', 'Appointment Cancelled'), ('rating_received', 'Rating Received'), ('customer_completed', 'Customer Marked Completed'), ('new_review', 'New Review Received')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['worker', 'is_read', 'created_at'], name='jobs_notifi_worker__23e1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['customer', 'is_read', 'created_at'], name='jobs_notifi_custome_4f25b0_idx'),
        ),
    ]
