# Generated by Django 5.1.1 on 2025-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_notification_worker_rating_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='jobs_notifi_worker__23e1c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='jobs_notifi_custome_4f25b0_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='worker_rating',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_request', 'Appointment Request'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_completed', 'Appointment Completed'), ('appointment_cancelled', 'Appointment Cancelled'), ('rating_received', 'Rating Received')], max_length=30),
        ),
    ]
