# Generated by Django 5.1.1 on 2025-10-03 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_remove_notification_jobs_notifi_worker__23e1c7_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_night_shift',
            field=models.BooleanField(default=False, help_text='Whether night shift extra charges apply'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity/hours for pricing calculation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total calculated price for the service', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_subtask',
            field=models.ForeignKey(blank=True, help_text='Selected service and pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.workersubtaskpricing'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'status'], name='jobs_appoin_custome_9e1c16_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['worker', 'status'], name='jobs_appoin_worker__54f5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='jobs_appoin_appoint_c11d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='jobs_appoin_created_303973_idx'),
        ),
    ]
