# Generated by Django 5.1.1 on 2025-10-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_alter_appointment_options_appointment_is_night_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_request', 'Appointment Request'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_completed', 'Appointment Completed'), ('appointment_cancelled', 'Appointment Cancelled'), ('rating_received', 'Rating Received'), ('customer_completed', 'Customer Marked Completed')], max_length=30),
        ),
    ]
