# Generated by Django 5.1.1 on 2025-10-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_subtask_created_by_subtask_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerrating',
            unique_together={('customer', 'worker')},
        ),
        migrations.AlterField(
            model_name='workerrating',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='jobs.appointment'),
        ),
    ]
