# Generated by Django 5.1.1 on 2025-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_worker_rejection_reason_worker_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='last_rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
