# Generated by Django 5.1.1 on 2025-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_worker_last_rejection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], default='day', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30),
        ),
    ]
