# Generated by Django 5.1.1 on 2025-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_alter_appointment_shift_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='delay_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='delay_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
