# Generated by Django 5.1.1 on 2025-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_appointment_delay_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
    ]
