# Generated by Django 5.1.1 on 2025-10-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_appointment_is_delayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='total_ratings',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, help_text="Time slot in format '14:00-16:00'", max_length=20, null=True),
        ),
    ]
