# Generated by Django 5.1.1 on 2025-10-28 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_remove_worker_total_ratings_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerrating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workerrating',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='jobs.appointment'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workerrating',
            unique_together={('customer', 'appointment')},
        ),
    ]
