# Generated by Django 5.1.1 on 2025-10-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_alter_workerrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerrating',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='workerrating',
            unique_together={('appointment', 'customer')},
        ),
        migrations.AlterField(
            model_name='workerrating',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
