# Generated by Django 5.1.1 on 2025-10-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_alter_workerrating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersubtaskpricing',
            name='max_hours',
            field=models.PositiveIntegerField(default=8, help_text='Maximum hours per day'),
        ),
        migrations.AddField(
            model_name='workersubtaskpricing',
            name='unit_label',
            field=models.CharField(blank=True, help_text="Label for unit (e.g., 'sq ft', 'rooms', 'items')", max_length=50),
        ),
    ]
