# Generated by Django 5.1.1 on 2025-11-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_workersubtaskpricing_max_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='previous_latitude',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='previous_location_address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='previous_location_updated_at',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='previous_longitude',
        ),
    ]
