# Generated by Django 5.1.1 on 2025-11-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_customer_gender_worker_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('worker', 'Worker'), ('system', 'System')], help_text='Who cancelled the appointment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_by',
            field=models.CharField(blank=True, help_text='Who rejected the appointment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected by Worker'), ('cancelled', 'Cancelled by Customer'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending_payment', max_length=30),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['cancelled_by', 'cancelled_at'], name='jobs_appoin_cancell_a64e17_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['rejected_by', 'rejected_at'], name='jobs_appoin_rejecte_3de9af_idx'),
        ),
    ]
