# Generated by Django 5.1.1 on 2025-11-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_appointment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='jobs_appoin_cancell_a64e17_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='jobs_appoin_rejecte_3de9af_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30),
        ),
    ]
