# Generated by Django 5.1.1 on 2025-11-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
