# Generated by Django 5.1.1 on 2025-11-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_servicecategory_is_custom_alter_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='is_custom',
        ),
    ]
