# Generated by Django 5.1.1 on 2025-08-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_projectcategory_useractivity_recoveruser_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='RecoverUser',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
