# Generated by Django 5.1.1 on 2025-10-16 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('jobs', '0037_worker_rejection_reason_worker_verification_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('worker_approved', 'Worker Approved'), ('worker_rejected', 'Worker Rejected'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('plain_text_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification_updates', models.BooleanField(default=True)),
                ('email_appointment_requests', models.BooleanField(default=True)),
                ('email_appointment_updates', models.BooleanField(default=True)),
                ('email_promotions', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='email_recipient',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admindashboardsettings',
            name='admin_email',
            field=models.EmailField(default='admin@bluecaller.com', max_length=254),
        ),
        migrations.AddField(
            model_name='admindashboardsettings',
            name='email_from_name',
            field=models.CharField(default='BlueCaller Team', max_length=100),
        ),
        migrations.AddField(
            model_name='admindashboardsettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admindashboardsettings',
            name='support_email',
            field=models.EmailField(default='support@bluecaller.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VERIFY', 'Verify'), ('REJECT', 'Reject')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin_user', 'created_at'], name='admin_dashb_admin_u_cf9ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', 'created_at'], name='admin_dashb_action_f0c61c_idx'),
        ),
        migrations.AddField(
            model_name='workernotificationsettings',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='jobs.worker'),
        ),
    ]
