# Generated by Django 5.1.1 on 2025-10-13 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0002_otp_email_alter_otp_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'purpose', 'created_at'], name='otp_auth_ot_email_7d7cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='otp_auth_ot_expires_91219a_idx'),
        ),
    ]
